services:

    kyoushu_common.routing.router_cache:
        class: Kyoushu\CommonBundle\Routing\RouterCache
        arguments:
            - @router

    kyoushu_common.routing.dynamic_route_loader:
        class: Kyoushu\CommonBundle\Routing\DynamicRouteLoader
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: routing.loader }

    kyoushu_common.upload.handler:
        class: Kyoushu\CommonBundle\Upload\UploadHandler
        arguments:
            - "%kernel.root_dir%/../web"

    kyoushu_common.event_listener.entity_subscriber:
       class: Kyoushu\CommonBundle\EventListener\EntitySubscriber
       arguments:
           - @kyoushu_common.routing.router_cache
           - @kyoushu_common.upload.handler
       tags:
           - { name: doctrine.event_subscriber, connection: default }